version: '3.8'

services:
  node:
    image: ariwijayaikd/test-monorepo:node-latest
    build:
      context: ./node
      dockerfile: node.Dockerfile
    container_name: node-monorepo
    ports:
      - "3000:3000"
    restart: always
    logging:
      options:
        max-size: "10m"

  go:
    image: ariwijayaikd/test-monorepo:go-latest
    build:
      context: ./go
      dockerfile: go.Dockerfile
    container_name: go-monorepo
    ports:
      - "8080:8080"
    restart: always
    logging:
      options:
        max-size: "10m"