apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-monorepo
  labels:
    app: go-monorepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-monorepo
  template:
    metadata:
      labels:
        app: go-monorepo
    spec:
      containers:
        - name: go-monorepo
          image: ghcr.io/ariwijayaikd/test-monorepo:go-latest
          ports:
            - containerPort: 8080
