name: Deploy to GKE

on:
  push:
    branches: [ none ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up gcloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure gcloud
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

    - name: Install GKE gcloud auth plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Apply Kubernetes manifests
      working-directory: ${{ github.workspace }}
      run: |
        kubectl apply -f ./k8s/
